version: "3"

services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./code:/var/www/html

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'
      
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=false
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    mem_limit: 1g
#    ports:
#        - "9200:9200"
#    labels:
#      - 'traefik.backend=es'
#      - 'traefik.port=9200'
#      - 'traefik.frontend.rule=Host:es.${PROJECT_BASE_URL}'

  mariadb:
    volumes:
      - ./db:/var/lib/mysql # I want to manage volumes manually.

  nginx:
    volumes:
      - ./code:/var/www/html

volumes:
  codebase:
